#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Cuoi_Ky
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LTUDQL1")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertKhoi(Khoi instance);
    partial void UpdateKhoi(Khoi instance);
    partial void DeleteKhoi(Khoi instance);
    partial void InsertQueQuan(QueQuan instance);
    partial void UpdateQueQuan(QueQuan instance);
    partial void DeleteQueQuan(QueQuan instance);
    partial void InsertDeThi(DeThi instance);
    partial void UpdateDeThi(DeThi instance);
    partial void DeleteDeThi(DeThi instance);
    partial void InsertKetQuaThi(KetQuaThi instance);
    partial void UpdateKetQuaThi(KetQuaThi instance);
    partial void DeleteKetQuaThi(KetQuaThi instance);
    partial void InsertKyThiThu(KyThiThu instance);
    partial void UpdateKyThiThu(KyThiThu instance);
    partial void DeleteKyThiThu(KyThiThu instance);
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertKyThi(KyThi instance);
    partial void UpdateKyThi(KyThi instance);
    partial void DeleteKyThi(KyThi instance);
    partial void InsertLichThi(LichThi instance);
    partial void UpdateLichThi(LichThi instance);
    partial void DeleteLichThi(LichThi instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Do_An_Cuoi_Ky.Properties.Settings.Default.LTUDQL1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Khoi> Khois
		{
			get
			{
				return this.GetTable<Khoi>();
			}
		}
		
		public System.Data.Linq.Table<QueQuan> QueQuans
		{
			get
			{
				return this.GetTable<QueQuan>();
			}
		}
		
		public System.Data.Linq.Table<DeThi> DeThis
		{
			get
			{
				return this.GetTable<DeThi>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaThi> KetQuaThis
		{
			get
			{
				return this.GetTable<KetQuaThi>();
			}
		}
		
		public System.Data.Linq.Table<KyThiThu> KyThiThus
		{
			get
			{
				return this.GetTable<KyThiThu>();
			}
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<KyThi> KyThis
		{
			get
			{
				return this.GetTable<KyThi>();
			}
		}
		
		public System.Data.Linq.Table<LichThi> LichThis
		{
			get
			{
				return this.GetTable<LichThi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Stt;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _LoaiTaiKhoan;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Sdt;
		
		private string _QueQuan;
		
		private string _Khoi;
		
		private string _Lop;
		
		private EntitySet<KetQuaThi> _KetQuaThis;
		
		private EntityRef<Khoi> _Khoi1;
		
		private EntityRef<QueQuan> _QueQuan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSttChanging(int value);
    partial void OnSttChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnLoaiTaiKhoanChanging(string value);
    partial void OnLoaiTaiKhoanChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnKhoiChanging(string value);
    partial void OnKhoiChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    #endregion
		
		public User()
		{
			this._KetQuaThis = new EntitySet<KetQuaThi>(new Action<KetQuaThi>(this.attach_KetQuaThis), new Action<KetQuaThi>(this.detach_KetQuaThis));
			this._Khoi1 = default(EntityRef<Khoi>);
			this._QueQuan1 = default(EntityRef<QueQuan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Stt
		{
			get
			{
				return this._Stt;
			}
			set
			{
				if ((this._Stt != value))
				{
					this.OnSttChanging(value);
					this.SendPropertyChanging();
					this._Stt = value;
					this.SendPropertyChanged("Stt");
					this.OnSttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTaiKhoan", DbType="Char(10)")]
		public string LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan;
			}
			set
			{
				if ((this._LoaiTaiKhoan != value))
				{
					this.OnLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._LoaiTaiKhoan = value;
					this.SendPropertyChanged("LoaiTaiKhoan");
					this.OnLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(20)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="Char(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(20)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					if (this._QueQuan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoi", DbType="Char(2)")]
		public string Khoi
		{
			get
			{
				return this._Khoi;
			}
			set
			{
				if ((this._Khoi != value))
				{
					if (this._Khoi1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoiChanging(value);
					this.SendPropertyChanging();
					this._Khoi = value;
					this.SendPropertyChanged("Khoi");
					this.OnKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="Char(10)")]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_KetQuaThi", Storage="_KetQuaThis", ThisKey="Stt,TaiKhoan", OtherKey="ID,TaiKhoan")]
		public EntitySet<KetQuaThi> KetQuaThis
		{
			get
			{
				return this._KetQuaThis;
			}
			set
			{
				this._KetQuaThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_User", Storage="_Khoi1", ThisKey="Khoi", OtherKey="TenKhoi", IsForeignKey=true)]
		public Khoi Khoi1
		{
			get
			{
				return this._Khoi1.Entity;
			}
			set
			{
				Khoi previousValue = this._Khoi1.Entity;
				if (((previousValue != value) 
							|| (this._Khoi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoi1.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Khoi1.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._Khoi = value.TenKhoi;
					}
					else
					{
						this._Khoi = default(string);
					}
					this.SendPropertyChanged("Khoi1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QueQuan_User", Storage="_QueQuan1", ThisKey="QueQuan", OtherKey="TenTinhThanh", IsForeignKey=true)]
		public QueQuan QueQuan1
		{
			get
			{
				return this._QueQuan1.Entity;
			}
			set
			{
				QueQuan previousValue = this._QueQuan1.Entity;
				if (((previousValue != value) 
							|| (this._QueQuan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QueQuan1.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._QueQuan1.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._QueQuan = value.TenTinhThanh;
					}
					else
					{
						this._QueQuan = default(string);
					}
					this.SendPropertyChanged("QueQuan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoi")]
	public partial class Khoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenKhoi;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenKhoiChanging(string value);
    partial void OnTenKhoiChanged();
    #endregion
		
		public Khoi()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoi", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenKhoi
		{
			get
			{
				return this._TenKhoi;
			}
			set
			{
				if ((this._TenKhoi != value))
				{
					this.OnTenKhoiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoi = value;
					this.SendPropertyChanged("TenKhoi");
					this.OnTenKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_User", Storage="_Users", ThisKey="TenKhoi", OtherKey="Khoi")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Khoi1 = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Khoi1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QueQuan")]
	public partial class QueQuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTinhThanh;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTinhThanhChanging(string value);
    partial void OnTenTinhThanhChanged();
    #endregion
		
		public QueQuan()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhThanh", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTinhThanh
		{
			get
			{
				return this._TenTinhThanh;
			}
			set
			{
				if ((this._TenTinhThanh != value))
				{
					this.OnTenTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TenTinhThanh = value;
					this.SendPropertyChanged("TenTinhThanh");
					this.OnTenTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QueQuan_User", Storage="_Users", ThisKey="TenTinhThanh", OtherKey="QueQuan")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.QueQuan1 = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.QueQuan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeThi")]
	public partial class DeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDe;
		
		private string _MonHoc;
		
		private string _MaMonHoc;
		
		private System.Nullable<int> _Cau01;
		
		private System.Nullable<int> _Cau02;
		
		private System.Nullable<int> _Cau03;
		
		private System.Nullable<int> _Cau04;
		
		private System.Nullable<int> _Cau05;
		
		private System.Nullable<int> _Cau06;
		
		private System.Nullable<int> _Cau07;
		
		private System.Nullable<int> _Cau08;
		
		private System.Nullable<int> _Cau09;
		
		private System.Nullable<int> _Cau10;
		
		private EntitySet<KetQuaThi> _KetQuaThis;
		
		private EntityRef<CauHoi> _CauHoi;
		
		private EntityRef<CauHoi> _CauHoi1;
		
		private EntityRef<CauHoi> _CauHoi2;
		
		private EntityRef<CauHoi> _CauHoi3;
		
		private EntityRef<CauHoi> _CauHoi4;
		
		private EntityRef<CauHoi> _CauHoi5;
		
		private EntityRef<CauHoi> _CauHoi6;
		
		private EntityRef<CauHoi> _CauHoi7;
		
		private EntityRef<CauHoi> _CauHoi8;
		
		private EntityRef<CauHoi> _CauHoi9;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeChanging(string value);
    partial void OnMaDeChanged();
    partial void OnMonHocChanging(string value);
    partial void OnMonHocChanged();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnCau01Changing(System.Nullable<int> value);
    partial void OnCau01Changed();
    partial void OnCau02Changing(System.Nullable<int> value);
    partial void OnCau02Changed();
    partial void OnCau03Changing(System.Nullable<int> value);
    partial void OnCau03Changed();
    partial void OnCau04Changing(System.Nullable<int> value);
    partial void OnCau04Changed();
    partial void OnCau05Changing(System.Nullable<int> value);
    partial void OnCau05Changed();
    partial void OnCau06Changing(System.Nullable<int> value);
    partial void OnCau06Changed();
    partial void OnCau07Changing(System.Nullable<int> value);
    partial void OnCau07Changed();
    partial void OnCau08Changing(System.Nullable<int> value);
    partial void OnCau08Changed();
    partial void OnCau09Changing(System.Nullable<int> value);
    partial void OnCau09Changed();
    partial void OnCau10Changing(System.Nullable<int> value);
    partial void OnCau10Changed();
    #endregion
		
		public DeThi()
		{
			this._KetQuaThis = new EntitySet<KetQuaThi>(new Action<KetQuaThi>(this.attach_KetQuaThis), new Action<KetQuaThi>(this.detach_KetQuaThis));
			this._CauHoi = default(EntityRef<CauHoi>);
			this._CauHoi1 = default(EntityRef<CauHoi>);
			this._CauHoi2 = default(EntityRef<CauHoi>);
			this._CauHoi3 = default(EntityRef<CauHoi>);
			this._CauHoi4 = default(EntityRef<CauHoi>);
			this._CauHoi5 = default(EntityRef<CauHoi>);
			this._CauHoi6 = default(EntityRef<CauHoi>);
			this._CauHoi7 = default(EntityRef<CauHoi>);
			this._CauHoi8 = default(EntityRef<CauHoi>);
			this._CauHoi9 = default(EntityRef<CauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDe", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDe
		{
			get
			{
				return this._MaDe;
			}
			set
			{
				if ((this._MaDe != value))
				{
					this.OnMaDeChanging(value);
					this.SendPropertyChanging();
					this._MaDe = value;
					this.SendPropertyChanged("MaDe");
					this.OnMaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonHoc", DbType="NVarChar(10)")]
		public string MonHoc
		{
			get
			{
				return this._MonHoc;
			}
			set
			{
				if ((this._MonHoc != value))
				{
					this.OnMonHocChanging(value);
					this.SendPropertyChanging();
					this._MonHoc = value;
					this.SendPropertyChanged("MonHoc");
					this.OnMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="Char(2)")]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau01", DbType="Int")]
		public System.Nullable<int> Cau01
		{
			get
			{
				return this._Cau01;
			}
			set
			{
				if ((this._Cau01 != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau01Changing(value);
					this.SendPropertyChanging();
					this._Cau01 = value;
					this.SendPropertyChanged("Cau01");
					this.OnCau01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau02", DbType="Int")]
		public System.Nullable<int> Cau02
		{
			get
			{
				return this._Cau02;
			}
			set
			{
				if ((this._Cau02 != value))
				{
					if (this._CauHoi1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau02Changing(value);
					this.SendPropertyChanging();
					this._Cau02 = value;
					this.SendPropertyChanged("Cau02");
					this.OnCau02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau03", DbType="Int")]
		public System.Nullable<int> Cau03
		{
			get
			{
				return this._Cau03;
			}
			set
			{
				if ((this._Cau03 != value))
				{
					if (this._CauHoi2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau03Changing(value);
					this.SendPropertyChanging();
					this._Cau03 = value;
					this.SendPropertyChanged("Cau03");
					this.OnCau03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau04", DbType="Int")]
		public System.Nullable<int> Cau04
		{
			get
			{
				return this._Cau04;
			}
			set
			{
				if ((this._Cau04 != value))
				{
					if (this._CauHoi3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau04Changing(value);
					this.SendPropertyChanging();
					this._Cau04 = value;
					this.SendPropertyChanged("Cau04");
					this.OnCau04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau05", DbType="Int")]
		public System.Nullable<int> Cau05
		{
			get
			{
				return this._Cau05;
			}
			set
			{
				if ((this._Cau05 != value))
				{
					if (this._CauHoi4.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau05Changing(value);
					this.SendPropertyChanging();
					this._Cau05 = value;
					this.SendPropertyChanged("Cau05");
					this.OnCau05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau06", DbType="Int")]
		public System.Nullable<int> Cau06
		{
			get
			{
				return this._Cau06;
			}
			set
			{
				if ((this._Cau06 != value))
				{
					if (this._CauHoi5.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau06Changing(value);
					this.SendPropertyChanging();
					this._Cau06 = value;
					this.SendPropertyChanged("Cau06");
					this.OnCau06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau07", DbType="Int")]
		public System.Nullable<int> Cau07
		{
			get
			{
				return this._Cau07;
			}
			set
			{
				if ((this._Cau07 != value))
				{
					if (this._CauHoi6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau07Changing(value);
					this.SendPropertyChanging();
					this._Cau07 = value;
					this.SendPropertyChanged("Cau07");
					this.OnCau07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau08", DbType="Int")]
		public System.Nullable<int> Cau08
		{
			get
			{
				return this._Cau08;
			}
			set
			{
				if ((this._Cau08 != value))
				{
					if (this._CauHoi7.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau08Changing(value);
					this.SendPropertyChanging();
					this._Cau08 = value;
					this.SendPropertyChanged("Cau08");
					this.OnCau08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau09", DbType="Int")]
		public System.Nullable<int> Cau09
		{
			get
			{
				return this._Cau09;
			}
			set
			{
				if ((this._Cau09 != value))
				{
					if (this._CauHoi8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau09Changing(value);
					this.SendPropertyChanging();
					this._Cau09 = value;
					this.SendPropertyChanged("Cau09");
					this.OnCau09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau10", DbType="Int")]
		public System.Nullable<int> Cau10
		{
			get
			{
				return this._Cau10;
			}
			set
			{
				if ((this._Cau10 != value))
				{
					if (this._CauHoi9.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCau10Changing(value);
					this.SendPropertyChanging();
					this._Cau10 = value;
					this.SendPropertyChanged("Cau10");
					this.OnCau10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_KetQuaThi", Storage="_KetQuaThis", ThisKey="MaDe", OtherKey="MaDe")]
		public EntitySet<KetQuaThi> KetQuaThis
		{
			get
			{
				return this._KetQuaThis;
			}
			set
			{
				this._KetQuaThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi", Storage="_CauHoi", ThisKey="Cau01", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.DeThis.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.DeThis.Add(this);
						this._Cau01 = value.ID;
					}
					else
					{
						this._Cau01 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi1", Storage="_CauHoi1", ThisKey="Cau02", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi1
		{
			get
			{
				return this._CauHoi1.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi1.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi1.Entity = null;
						previousValue.DeThis1.Remove(this);
					}
					this._CauHoi1.Entity = value;
					if ((value != null))
					{
						value.DeThis1.Add(this);
						this._Cau02 = value.ID;
					}
					else
					{
						this._Cau02 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi2", Storage="_CauHoi2", ThisKey="Cau03", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi2
		{
			get
			{
				return this._CauHoi2.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi2.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi2.Entity = null;
						previousValue.DeThis2.Remove(this);
					}
					this._CauHoi2.Entity = value;
					if ((value != null))
					{
						value.DeThis2.Add(this);
						this._Cau03 = value.ID;
					}
					else
					{
						this._Cau03 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi3", Storage="_CauHoi3", ThisKey="Cau04", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi3
		{
			get
			{
				return this._CauHoi3.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi3.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi3.Entity = null;
						previousValue.DeThis3.Remove(this);
					}
					this._CauHoi3.Entity = value;
					if ((value != null))
					{
						value.DeThis3.Add(this);
						this._Cau04 = value.ID;
					}
					else
					{
						this._Cau04 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi4", Storage="_CauHoi4", ThisKey="Cau05", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi4
		{
			get
			{
				return this._CauHoi4.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi4.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi4.Entity = null;
						previousValue.DeThis4.Remove(this);
					}
					this._CauHoi4.Entity = value;
					if ((value != null))
					{
						value.DeThis4.Add(this);
						this._Cau05 = value.ID;
					}
					else
					{
						this._Cau05 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi5", Storage="_CauHoi5", ThisKey="Cau06", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi5
		{
			get
			{
				return this._CauHoi5.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi5.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi5.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi5.Entity = null;
						previousValue.DeThis5.Remove(this);
					}
					this._CauHoi5.Entity = value;
					if ((value != null))
					{
						value.DeThis5.Add(this);
						this._Cau06 = value.ID;
					}
					else
					{
						this._Cau06 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi5");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi6", Storage="_CauHoi6", ThisKey="Cau07", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi6
		{
			get
			{
				return this._CauHoi6.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi6.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi6.Entity = null;
						previousValue.DeThis6.Remove(this);
					}
					this._CauHoi6.Entity = value;
					if ((value != null))
					{
						value.DeThis6.Add(this);
						this._Cau07 = value.ID;
					}
					else
					{
						this._Cau07 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi6");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi7", Storage="_CauHoi7", ThisKey="Cau08", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi7
		{
			get
			{
				return this._CauHoi7.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi7.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi7.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi7.Entity = null;
						previousValue.DeThis7.Remove(this);
					}
					this._CauHoi7.Entity = value;
					if ((value != null))
					{
						value.DeThis7.Add(this);
						this._Cau08 = value.ID;
					}
					else
					{
						this._Cau08 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi7");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi8", Storage="_CauHoi8", ThisKey="Cau09", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi8
		{
			get
			{
				return this._CauHoi8.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi8.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi8.Entity = null;
						previousValue.DeThis8.Remove(this);
					}
					this._CauHoi8.Entity = value;
					if ((value != null))
					{
						value.DeThis8.Add(this);
						this._Cau09 = value.ID;
					}
					else
					{
						this._Cau09 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi9", Storage="_CauHoi9", ThisKey="Cau10", OtherKey="ID", IsForeignKey=true)]
		public CauHoi CauHoi9
		{
			get
			{
				return this._CauHoi9.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi9.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi9.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi9.Entity = null;
						previousValue.DeThis9.Remove(this);
					}
					this._CauHoi9.Entity = value;
					if ((value != null))
					{
						value.DeThis9.Add(this);
						this._Cau10 = value.ID;
					}
					else
					{
						this._Cau10 = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi9");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaThi")]
	public partial class KetQuaThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Stt;
		
		private int _ID;
		
		private string _TaiKhoan;
		
		private string _MaDe;
		
		private System.Nullable<char> _Cau01;
		
		private System.Nullable<char> _Cau02;
		
		private System.Nullable<char> _Cau03;
		
		private System.Nullable<char> _Cau04;
		
		private System.Nullable<char> _Cau05;
		
		private System.Nullable<char> _Cau06;
		
		private System.Nullable<char> _Cau07;
		
		private System.Nullable<char> _Cau08;
		
		private System.Nullable<char> _Cau09;
		
		private System.Nullable<char> _Cau10;
		
		private int _DiemThi;
		
		private EntityRef<User> _User;
		
		private EntityRef<DeThi> _DeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSttChanging(int value);
    partial void OnSttChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMaDeChanging(string value);
    partial void OnMaDeChanged();
    partial void OnCau01Changing(System.Nullable<char> value);
    partial void OnCau01Changed();
    partial void OnCau02Changing(System.Nullable<char> value);
    partial void OnCau02Changed();
    partial void OnCau03Changing(System.Nullable<char> value);
    partial void OnCau03Changed();
    partial void OnCau04Changing(System.Nullable<char> value);
    partial void OnCau04Changed();
    partial void OnCau05Changing(System.Nullable<char> value);
    partial void OnCau05Changed();
    partial void OnCau06Changing(System.Nullable<char> value);
    partial void OnCau06Changed();
    partial void OnCau07Changing(System.Nullable<char> value);
    partial void OnCau07Changed();
    partial void OnCau08Changing(System.Nullable<char> value);
    partial void OnCau08Changed();
    partial void OnCau09Changing(System.Nullable<char> value);
    partial void OnCau09Changed();
    partial void OnCau10Changing(System.Nullable<char> value);
    partial void OnCau10Changed();
    partial void OnDiemThiChanging(int value);
    partial void OnDiemThiChanged();
    #endregion
		
		public KetQuaThi()
		{
			this._User = default(EntityRef<User>);
			this._DeThi = default(EntityRef<DeThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Stt
		{
			get
			{
				return this._Stt;
			}
			set
			{
				if ((this._Stt != value))
				{
					this.OnSttChanging(value);
					this.SendPropertyChanging();
					this._Stt = value;
					this.SendPropertyChanged("Stt");
					this.OnSttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDe", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string MaDe
		{
			get
			{
				return this._MaDe;
			}
			set
			{
				if ((this._MaDe != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeChanging(value);
					this.SendPropertyChanging();
					this._MaDe = value;
					this.SendPropertyChanged("MaDe");
					this.OnMaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau01", DbType="Char(1)")]
		public System.Nullable<char> Cau01
		{
			get
			{
				return this._Cau01;
			}
			set
			{
				if ((this._Cau01 != value))
				{
					this.OnCau01Changing(value);
					this.SendPropertyChanging();
					this._Cau01 = value;
					this.SendPropertyChanged("Cau01");
					this.OnCau01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau02", DbType="Char(1)")]
		public System.Nullable<char> Cau02
		{
			get
			{
				return this._Cau02;
			}
			set
			{
				if ((this._Cau02 != value))
				{
					this.OnCau02Changing(value);
					this.SendPropertyChanging();
					this._Cau02 = value;
					this.SendPropertyChanged("Cau02");
					this.OnCau02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau03", DbType="Char(1)")]
		public System.Nullable<char> Cau03
		{
			get
			{
				return this._Cau03;
			}
			set
			{
				if ((this._Cau03 != value))
				{
					this.OnCau03Changing(value);
					this.SendPropertyChanging();
					this._Cau03 = value;
					this.SendPropertyChanged("Cau03");
					this.OnCau03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau04", DbType="Char(1)")]
		public System.Nullable<char> Cau04
		{
			get
			{
				return this._Cau04;
			}
			set
			{
				if ((this._Cau04 != value))
				{
					this.OnCau04Changing(value);
					this.SendPropertyChanging();
					this._Cau04 = value;
					this.SendPropertyChanged("Cau04");
					this.OnCau04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau05", DbType="Char(1)")]
		public System.Nullable<char> Cau05
		{
			get
			{
				return this._Cau05;
			}
			set
			{
				if ((this._Cau05 != value))
				{
					this.OnCau05Changing(value);
					this.SendPropertyChanging();
					this._Cau05 = value;
					this.SendPropertyChanged("Cau05");
					this.OnCau05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau06", DbType="Char(1)")]
		public System.Nullable<char> Cau06
		{
			get
			{
				return this._Cau06;
			}
			set
			{
				if ((this._Cau06 != value))
				{
					this.OnCau06Changing(value);
					this.SendPropertyChanging();
					this._Cau06 = value;
					this.SendPropertyChanged("Cau06");
					this.OnCau06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau07", DbType="Char(1)")]
		public System.Nullable<char> Cau07
		{
			get
			{
				return this._Cau07;
			}
			set
			{
				if ((this._Cau07 != value))
				{
					this.OnCau07Changing(value);
					this.SendPropertyChanging();
					this._Cau07 = value;
					this.SendPropertyChanged("Cau07");
					this.OnCau07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau08", DbType="Char(1)")]
		public System.Nullable<char> Cau08
		{
			get
			{
				return this._Cau08;
			}
			set
			{
				if ((this._Cau08 != value))
				{
					this.OnCau08Changing(value);
					this.SendPropertyChanging();
					this._Cau08 = value;
					this.SendPropertyChanged("Cau08");
					this.OnCau08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau09", DbType="Char(1)")]
		public System.Nullable<char> Cau09
		{
			get
			{
				return this._Cau09;
			}
			set
			{
				if ((this._Cau09 != value))
				{
					this.OnCau09Changing(value);
					this.SendPropertyChanging();
					this._Cau09 = value;
					this.SendPropertyChanged("Cau09");
					this.OnCau09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cau10", DbType="Char(1)")]
		public System.Nullable<char> Cau10
		{
			get
			{
				return this._Cau10;
			}
			set
			{
				if ((this._Cau10 != value))
				{
					this.OnCau10Changing(value);
					this.SendPropertyChanging();
					this._Cau10 = value;
					this.SendPropertyChanged("Cau10");
					this.OnCau10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemThi", DbType="Int NOT NULL")]
		public int DiemThi
		{
			get
			{
				return this._DiemThi;
			}
			set
			{
				if ((this._DiemThi != value))
				{
					this.OnDiemThiChanging(value);
					this.SendPropertyChanging();
					this._DiemThi = value;
					this.SendPropertyChanged("DiemThi");
					this.OnDiemThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_KetQuaThi", Storage="_User", ThisKey="ID,TaiKhoan", OtherKey="Stt,TaiKhoan", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.KetQuaThis.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.KetQuaThis.Add(this);
						this._ID = value.Stt;
						this._TaiKhoan = value.TaiKhoan;
					}
					else
					{
						this._ID = default(int);
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_KetQuaThi", Storage="_DeThi", ThisKey="MaDe", OtherKey="MaDe", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.KetQuaThis.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.KetQuaThis.Add(this);
						this._MaDe = value.MaDe;
					}
					else
					{
						this._MaDe = default(string);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KyThiThu")]
	public partial class KyThiThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private System.Nullable<System.DateTime> _TuNgay;
		
		private System.Nullable<System.DateTime> _DenNgay;
		
		private string _DanhSachThiSinh;
		
		private string _DanhSachDeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnTuNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTuNgayChanged();
    partial void OnDenNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDenNgayChanged();
    partial void OnDanhSachThiSinhChanging(string value);
    partial void OnDanhSachThiSinhChanged();
    partial void OnDanhSachDeThiChanging(string value);
    partial void OnDanhSachDeThiChanged();
    #endregion
		
		public KyThiThu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="Date")]
		public System.Nullable<System.DateTime> TuNgay
		{
			get
			{
				return this._TuNgay;
			}
			set
			{
				if ((this._TuNgay != value))
				{
					this.OnTuNgayChanging(value);
					this.SendPropertyChanging();
					this._TuNgay = value;
					this.SendPropertyChanged("TuNgay");
					this.OnTuNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="Date")]
		public System.Nullable<System.DateTime> DenNgay
		{
			get
			{
				return this._DenNgay;
			}
			set
			{
				if ((this._DenNgay != value))
				{
					this.OnDenNgayChanging(value);
					this.SendPropertyChanging();
					this._DenNgay = value;
					this.SendPropertyChanged("DenNgay");
					this.OnDenNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhSachThiSinh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DanhSachThiSinh
		{
			get
			{
				return this._DanhSachThiSinh;
			}
			set
			{
				if ((this._DanhSachThiSinh != value))
				{
					this.OnDanhSachThiSinhChanging(value);
					this.SendPropertyChanging();
					this._DanhSachThiSinh = value;
					this.SendPropertyChanged("DanhSachThiSinh");
					this.OnDanhSachThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhSachDeThi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DanhSachDeThi
		{
			get
			{
				return this._DanhSachDeThi;
			}
			set
			{
				if ((this._DanhSachDeThi != value))
				{
					this.OnDanhSachDeThiChanging(value);
					this.SendPropertyChanging();
					this._DanhSachDeThi = value;
					this.SendPropertyChanged("DanhSachDeThi");
					this.OnDanhSachDeThiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MonHoc;
		
		private string _CauHoi1;
		
		private string _A;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private System.Nullable<char> _DapAnDung;
		
		private string _GoiY;
		
		private System.Nullable<int> _DoKho;
		
		private System.Nullable<int> _SoLanRaDe;
		
		private System.Nullable<int> _SoLanTraLoi;
		
		private System.Nullable<int> _SoLanTraLoiDung;
		
		private EntitySet<DeThi> _DeThis;
		
		private EntitySet<DeThi> _DeThis1;
		
		private EntitySet<DeThi> _DeThis2;
		
		private EntitySet<DeThi> _DeThis3;
		
		private EntitySet<DeThi> _DeThis4;
		
		private EntitySet<DeThi> _DeThis5;
		
		private EntitySet<DeThi> _DeThis6;
		
		private EntitySet<DeThi> _DeThis7;
		
		private EntitySet<DeThi> _DeThis8;
		
		private EntitySet<DeThi> _DeThis9;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMonHocChanging(string value);
    partial void OnMonHocChanged();
    partial void OnCauHoi1Changing(string value);
    partial void OnCauHoi1Changed();
    partial void OnAChanging(string value);
    partial void OnAChanged();
    partial void OnBChanging(string value);
    partial void OnBChanged();
    partial void OnCChanging(string value);
    partial void OnCChanged();
    partial void OnDChanging(string value);
    partial void OnDChanged();
    partial void OnDapAnDungChanging(System.Nullable<char> value);
    partial void OnDapAnDungChanged();
    partial void OnGoiYChanging(string value);
    partial void OnGoiYChanged();
    partial void OnDoKhoChanging(System.Nullable<int> value);
    partial void OnDoKhoChanged();
    partial void OnSoLanRaDeChanging(System.Nullable<int> value);
    partial void OnSoLanRaDeChanged();
    partial void OnSoLanTraLoiChanging(System.Nullable<int> value);
    partial void OnSoLanTraLoiChanged();
    partial void OnSoLanTraLoiDungChanging(System.Nullable<int> value);
    partial void OnSoLanTraLoiDungChanged();
    #endregion
		
		public CauHoi()
		{
			this._DeThis = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis), new Action<DeThi>(this.detach_DeThis));
			this._DeThis1 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis1), new Action<DeThi>(this.detach_DeThis1));
			this._DeThis2 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis2), new Action<DeThi>(this.detach_DeThis2));
			this._DeThis3 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis3), new Action<DeThi>(this.detach_DeThis3));
			this._DeThis4 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis4), new Action<DeThi>(this.detach_DeThis4));
			this._DeThis5 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis5), new Action<DeThi>(this.detach_DeThis5));
			this._DeThis6 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis6), new Action<DeThi>(this.detach_DeThis6));
			this._DeThis7 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis7), new Action<DeThi>(this.detach_DeThis7));
			this._DeThis8 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis8), new Action<DeThi>(this.detach_DeThis8));
			this._DeThis9 = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis9), new Action<DeThi>(this.detach_DeThis9));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonHoc", DbType="NVarChar(10)")]
		public string MonHoc
		{
			get
			{
				return this._MonHoc;
			}
			set
			{
				if ((this._MonHoc != value))
				{
					this.OnMonHocChanging(value);
					this.SendPropertyChanging();
					this._MonHoc = value;
					this.SendPropertyChanged("MonHoc");
					this.OnMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CauHoi", Storage="_CauHoi1", DbType="NVarChar(500)")]
		public string CauHoi1
		{
			get
			{
				return this._CauHoi1;
			}
			set
			{
				if ((this._CauHoi1 != value))
				{
					this.OnCauHoi1Changing(value);
					this.SendPropertyChanging();
					this._CauHoi1 = value;
					this.SendPropertyChanged("CauHoi1");
					this.OnCauHoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="NVarChar(100)")]
		public string A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(100)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(100)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(100)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="Char(1)")]
		public System.Nullable<char> DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiY", DbType="NVarChar(100)")]
		public string GoiY
		{
			get
			{
				return this._GoiY;
			}
			set
			{
				if ((this._GoiY != value))
				{
					this.OnGoiYChanging(value);
					this.SendPropertyChanging();
					this._GoiY = value;
					this.SendPropertyChanged("GoiY");
					this.OnGoiYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoKho", DbType="Int")]
		public System.Nullable<int> DoKho
		{
			get
			{
				return this._DoKho;
			}
			set
			{
				if ((this._DoKho != value))
				{
					this.OnDoKhoChanging(value);
					this.SendPropertyChanging();
					this._DoKho = value;
					this.SendPropertyChanged("DoKho");
					this.OnDoKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanRaDe", DbType="Int")]
		public System.Nullable<int> SoLanRaDe
		{
			get
			{
				return this._SoLanRaDe;
			}
			set
			{
				if ((this._SoLanRaDe != value))
				{
					this.OnSoLanRaDeChanging(value);
					this.SendPropertyChanging();
					this._SoLanRaDe = value;
					this.SendPropertyChanged("SoLanRaDe");
					this.OnSoLanRaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanTraLoi", DbType="Int")]
		public System.Nullable<int> SoLanTraLoi
		{
			get
			{
				return this._SoLanTraLoi;
			}
			set
			{
				if ((this._SoLanTraLoi != value))
				{
					this.OnSoLanTraLoiChanging(value);
					this.SendPropertyChanging();
					this._SoLanTraLoi = value;
					this.SendPropertyChanged("SoLanTraLoi");
					this.OnSoLanTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanTraLoiDung", DbType="Int")]
		public System.Nullable<int> SoLanTraLoiDung
		{
			get
			{
				return this._SoLanTraLoiDung;
			}
			set
			{
				if ((this._SoLanTraLoiDung != value))
				{
					this.OnSoLanTraLoiDungChanging(value);
					this.SendPropertyChanging();
					this._SoLanTraLoiDung = value;
					this.SendPropertyChanged("SoLanTraLoiDung");
					this.OnSoLanTraLoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi", Storage="_DeThis", ThisKey="ID", OtherKey="Cau01")]
		public EntitySet<DeThi> DeThis
		{
			get
			{
				return this._DeThis;
			}
			set
			{
				this._DeThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi1", Storage="_DeThis1", ThisKey="ID", OtherKey="Cau02")]
		public EntitySet<DeThi> DeThis1
		{
			get
			{
				return this._DeThis1;
			}
			set
			{
				this._DeThis1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi2", Storage="_DeThis2", ThisKey="ID", OtherKey="Cau03")]
		public EntitySet<DeThi> DeThis2
		{
			get
			{
				return this._DeThis2;
			}
			set
			{
				this._DeThis2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi3", Storage="_DeThis3", ThisKey="ID", OtherKey="Cau04")]
		public EntitySet<DeThi> DeThis3
		{
			get
			{
				return this._DeThis3;
			}
			set
			{
				this._DeThis3.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi4", Storage="_DeThis4", ThisKey="ID", OtherKey="Cau05")]
		public EntitySet<DeThi> DeThis4
		{
			get
			{
				return this._DeThis4;
			}
			set
			{
				this._DeThis4.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi5", Storage="_DeThis5", ThisKey="ID", OtherKey="Cau06")]
		public EntitySet<DeThi> DeThis5
		{
			get
			{
				return this._DeThis5;
			}
			set
			{
				this._DeThis5.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi6", Storage="_DeThis6", ThisKey="ID", OtherKey="Cau07")]
		public EntitySet<DeThi> DeThis6
		{
			get
			{
				return this._DeThis6;
			}
			set
			{
				this._DeThis6.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi7", Storage="_DeThis7", ThisKey="ID", OtherKey="Cau08")]
		public EntitySet<DeThi> DeThis7
		{
			get
			{
				return this._DeThis7;
			}
			set
			{
				this._DeThis7.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi8", Storage="_DeThis8", ThisKey="ID", OtherKey="Cau09")]
		public EntitySet<DeThi> DeThis8
		{
			get
			{
				return this._DeThis8;
			}
			set
			{
				this._DeThis8.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DeThi9", Storage="_DeThis9", ThisKey="ID", OtherKey="Cau10")]
		public EntitySet<DeThi> DeThis9
		{
			get
			{
				return this._DeThis9;
			}
			set
			{
				this._DeThis9.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
		
		private void attach_DeThis1(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi1 = this;
		}
		
		private void detach_DeThis1(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi1 = null;
		}
		
		private void attach_DeThis2(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi2 = this;
		}
		
		private void detach_DeThis2(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi2 = null;
		}
		
		private void attach_DeThis3(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi3 = this;
		}
		
		private void detach_DeThis3(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi3 = null;
		}
		
		private void attach_DeThis4(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi4 = this;
		}
		
		private void detach_DeThis4(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi4 = null;
		}
		
		private void attach_DeThis5(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi5 = this;
		}
		
		private void detach_DeThis5(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi5 = null;
		}
		
		private void attach_DeThis6(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi6 = this;
		}
		
		private void detach_DeThis6(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi6 = null;
		}
		
		private void attach_DeThis7(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi7 = this;
		}
		
		private void detach_DeThis7(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi7 = null;
		}
		
		private void attach_DeThis8(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi8 = this;
		}
		
		private void detach_DeThis8(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi8 = null;
		}
		
		private void attach_DeThis9(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi9 = this;
		}
		
		private void detach_DeThis9(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi9 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KyThi")]
	public partial class KyThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyThi;
		
		private System.Nullable<System.DateTime> _NgayThi;
		
		private string _DanhSachThiSinh;
		
		private string _DanhSachDeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnNgayThiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThiChanged();
    partial void OnDanhSachThiSinhChanging(string value);
    partial void OnDanhSachThiSinhChanged();
    partial void OnDanhSachDeThiChanging(string value);
    partial void OnDanhSachDeThiChanged();
    #endregion
		
		public KyThi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhSachThiSinh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DanhSachThiSinh
		{
			get
			{
				return this._DanhSachThiSinh;
			}
			set
			{
				if ((this._DanhSachThiSinh != value))
				{
					this.OnDanhSachThiSinhChanging(value);
					this.SendPropertyChanging();
					this._DanhSachThiSinh = value;
					this.SendPropertyChanged("DanhSachThiSinh");
					this.OnDanhSachThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhSachDeThi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DanhSachDeThi
		{
			get
			{
				return this._DanhSachDeThi;
			}
			set
			{
				if ((this._DanhSachDeThi != value))
				{
					this.OnDanhSachDeThiChanging(value);
					this.SendPropertyChanging();
					this._DanhSachDeThi = value;
					this.SendPropertyChanged("DanhSachDeThi");
					this.OnDanhSachDeThiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichThi")]
	public partial class LichThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _TaiKhoan;
		
		private string _MaKyThi;
		
		private System.Nullable<System.DateTime> _NgayThi;
		
		private System.TimeSpan _GioThi;
		
		private string _PhongThi;
		
		private string _MonThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMaKyThiChanging(string value);
    partial void OnMaKyThiChanged();
    partial void OnNgayThiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThiChanged();
    partial void OnGioThiChanging(System.TimeSpan value);
    partial void OnGioThiChanged();
    partial void OnPhongThiChanging(string value);
    partial void OnPhongThiChanged();
    partial void OnMonThiChanging(string value);
    partial void OnMonThiChanged();
    #endregion
		
		public LichThi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="Char(20)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyThi", DbType="NChar(4)")]
		public string MaKyThi
		{
			get
			{
				return this._MaKyThi;
			}
			set
			{
				if ((this._MaKyThi != value))
				{
					this.OnMaKyThiChanging(value);
					this.SendPropertyChanging();
					this._MaKyThi = value;
					this.SendPropertyChanged("MaKyThi");
					this.OnMaKyThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioThi", DbType="Time NOT NULL", IsPrimaryKey=true)]
		public System.TimeSpan GioThi
		{
			get
			{
				return this._GioThi;
			}
			set
			{
				if ((this._GioThi != value))
				{
					this.OnGioThiChanging(value);
					this.SendPropertyChanging();
					this._GioThi = value;
					this.SendPropertyChanged("GioThi");
					this.OnGioThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongThi", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PhongThi
		{
			get
			{
				return this._PhongThi;
			}
			set
			{
				if ((this._PhongThi != value))
				{
					this.OnPhongThiChanging(value);
					this.SendPropertyChanging();
					this._PhongThi = value;
					this.SendPropertyChanged("PhongThi");
					this.OnPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonThi", DbType="NVarChar(10)")]
		public string MonThi
		{
			get
			{
				return this._MonThi;
			}
			set
			{
				if ((this._MonThi != value))
				{
					this.OnMonThiChanging(value);
					this.SendPropertyChanging();
					this._MonThi = value;
					this.SendPropertyChanged("MonThi");
					this.OnMonThiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
